[package]
name = "occt-sys"
version = { workspace = true }
edition = { workspace = true }
links = "occt"

[dependencies]
error-location = { workspace = true }
goblin         = { workspace = true }
libloading     = { workspace = true }
mesh           = { workspace = true }
thiserror      = { workspace = true }

[dev-dependencies]
tempfile       = { workspace = true }

[build-dependencies]
cc = { workspace = true }

[lints]
workspace = true
